### ISSUE TITLE
Certificate Error + Usage documentation

### ISSUE THREAD

**Issue by gkarthiks** [razee-io/Kapitan-delta#6]
I have deployed this via `kubectl apply -f https://github.com/razee-io/Kapitan-delta/releases/latest/download/resource.yaml` from the `razee-io` site inside my corporate proxy. 

Having issues in "Self certificate chain". Below attached the deployment details.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '5'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"razee.io/commit-sha":"a1fe08e0ed170c80ba8c37c1d9e5a4e775f01b24","razee.io/git-repo":"https://github.com/razee-io/Kapitan-delta.git","version":"a1fe08e0ed170c80ba8c37c1d9e5a4e775f01b24"},"name":"kapitan-delta","namespace":"razee"},"spec":{"replicas":1,"revisionHistoryLimit":0,"selector":{"matchLabels":{"app":"kapitan-delta"}},"strategy":{"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"kapitan-delta"},"name":"kapitan-delta"},"spec":{"containers":[{"env":[{"name":"ENFORCE_INTERVAL_MINUTES","value":"5"}],"image":"quay.io/razee/kapitan-delta:0.0.10","imagePullPolicy":"Always","livenessProbe":{"exec":{"command":["sh/liveness.sh"]},"failureThreshold":1,"initialDelaySeconds":30,"periodSeconds":300,"timeoutSeconds":30},"name":"kapitan-delta","resources":{"limits":{"cpu":"100m","memory":"150Mi"},"requests":{"cpu":"40m","memory":"50Mi"}},"volumeMounts":[{"mountPath":"/usr/src/app/resource-uris","name":"resource-uris"}]}],"serviceAccountName":"kapitan-sa","volumes":[{"configMap":{"defaultMode":420,"name":"kapitan-delta-resource-uris"},"name":"resource-uris"}]}}}}
    razee.io/commit-sha: a1fe08e0ed170c80ba8c37c1d9e5a4e775f01b24
    razee.io/git-repo: 'https://github.com/razee-io/Kapitan-delta.git'
    version: a1fe08e0ed170c80ba8c37c1d9e5a4e775f01b24
  creationTimestamp: '2019-06-18T03:00:57Z'
  generation: 5
  labels:
    app: kapitan-delta
  name: kapitan-delta
  namespace: razee
  resourceVersion: '339011407'
  selfLink: /apis/apps/v1/namespaces/razee/deployments/kapitan-delta
  uid: 4b935de2-9175-11e9-98ce-fa163e5b8f19
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kapitan-delta
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kapitan-delta
      name: kapitan-delta
    spec:
      containers:
        - env:
            - name: ENFORCE_INTERVAL_MINUTES
              value: '5'
            - name: HTTPS_PROXY
              value: {-REDACTED-}
            - name: HTTP_PROXY
              value: {-REDACTED-}
            - name: NO_PROXY
              value: {-REDACTED-}
            - name: http_proxy
              value: {-REDACTED-}
            - name: https_proxy
              value: {-REDACTED-}
            - name: no_proxy
              value: {-REDACTED-}
            - name: npm_config_strict-ssl
              value: 'false'
            - name: npm_config_ca
              value: 'null'
            - name: npm_config_https_proxy
              value: {-REDACTED-}
          image: 'quay.io/razee/kapitan-delta:0.0.10'
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - sh/liveness.sh
            failureThreshold: 1
            initialDelaySeconds: 30
            periodSeconds: 300
            successThreshold: 1
            timeoutSeconds: 30
          name: kapitan-delta
          resources:
            limits:
              cpu: 100m
              memory: 150Mi
            requests:
              cpu: 40m
              memory: 50Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/src/app/resource-uris
              name: resource-uris
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kapitan-sa
      serviceAccountName: kapitan-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: kapitan-delta-resource-uris
          name: resource-uris
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-06-18T03:17:10Z'
      lastUpdateTime: '2019-06-18T03:17:10Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2019-06-18T03:00:57Z'
      lastUpdateTime: '2019-06-18T04:00:12Z'
      message: ReplicaSet "kapitan-delta-86c6874448" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

The error message
```json
> delta@0.0.1 start /usr/src/app
> node src/index.js

{"name":"delta","hostname":"kapitan-delta-86c6874448-gbz2m","pid":18,"level":30,"msg":"Updating https://github.com/razee-io/FeatureFlagSetLD/releases/latest/download/resource.yaml","time":"2019-06-18T04:00:09.383Z","v":0 }
(node:18) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
{"name":"delta","hostname":"kapitan-delta-86c6874448-gbz2m","pid":18,"level":50,"err":{"message":"Error: self signed certificate in certificate chain","name":"RequestError","stack":"RequestError: Error: self signed certificate in certificate chain\n    at new RequestError (/usr/src/app/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/usr/src/app/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/usr/src/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:200:13)\n    at Request.onRequestError (/usr/src/app/node_modules/request/request.js:881:8)\n    at ClientRequest.emit (events.js:200:13)\n    at TLSSocket.socketErrorListener (_http_client.js:410:9)\n    at TLSSocket.emit (events.js:200:13)\n    at emitErrorNT (internal/streams/destroy.js:91:8)"},"msg":"Error: self signed certificate in certificate chain","time":"2019-06-18T04:01:26.323Z","v":0}
```

As shown in the deployment file, I've also set the npm config env variables as well. But no help on with that.

Can you please help me in resolving that. Also it would be great to know what's the use of the "kapitan-delta" ? is this only used for installing the `FeatureFlagSetLD`, `ManagedSet`, `MustacheTemplate`, `RemoteResource` and `RemoteResourceS3` ?

**Comment by alewitt2** [comment]
So im not sure how to fix your issue, we havent done any work behind https or proxy. All kapitan-delta is doing is installing/updating FeatureFlagSetLD, ManagedSet, MustacheTemplate, RemoteResource and RemoteResourceS3. So if you want to just install them manually, you dont really need kapitan delta

**Comment by alewitt2** [comment]
to manually install just do `kubectl apply -f https://github.com/razee-io/<name>/releases/latest/download/resource.yaml`

**Comment by gkarthiks** [comment]
@alewitt2  thanks for the quick turnaround. I installed them manually. And I have waited for quiet some time. But same issue with `remoteresource-controller` as well. So deployed both the api and razeedash manually. Thanks for the support again.

**Comment by gkarthiks** [comment]
one quick question though, is there a way we can override the GitHub to any other on-prem source code control systems, specifically like GitLab?

**Comment by gkarthiks** [comment]
I tried setting the env variables to gitlab. But didn't work.

**Comment by alewitt2** [comment]
ok so several things:

1. what does you setup look like. im not sure i fully understand what you mean when you say `inside my corporate proxy`. I looks like you are able to apply the yaml using kubectl and kube is able to pull the image. So please describe what is unique about your networking that isnt allowing requests to go out in the pod itself.
1. what do you mean `override the GitHub`. are you talking about on the razeedash/razeedash-api side?
1. Which env variables did you try setting to gitlab?

**Comment by alewitt2** [comment]
also i found this, not sure if its helpful to you https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain
